<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RubyBot.Contracts\RubyBot.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
      <HintPath>
        C:\Users\verfix\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\10.0.7\lib\net10.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>C:\Users\verfix\.nuget\packages\microsoft.extensions.logging.abstractions\10.0.7\lib\net10.0\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>