<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RubyBot.Application\RubyBot.Application.csproj" />
    <ProjectReference Include="..\RubyBot.Contracts\RubyBot.Contracts.csproj" />
  </ItemGroup>

</Project>
