<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <!-- Active Dependencies -->
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
  </ItemGroup>
</Project>